#! /bin/sh

#
#
#    ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ 
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░   
#     ░            ░               ░           ░   
#          ░                                       
#

pgrep -x sxhkd > /dev/null || sxhkd &

##################################################################
#                     WM CONFIG                                   #
##################################################################
# wm config
bspc config border_width 0
bspc config window_gap 13
#bspc config top_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out + $(bspc config window_gap)))
# bspc config bottom_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out))


#bspc config focus_follows_pointer true

##################################################################
#                     GENERAL SETTINGS                            #
##################################################################

bspc monitor -d 1 2 3 4 5 6

# rules
bspc rule -a Zathura state=tiled

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a min desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=off
bspc rule -a Screenkey manage=off
#bspc rule -a Thunar state=floating follow=off focus=off
#bspc rule -a Viewnior state=floating follow=off foc



##################################################################
#                     AUTOSTART APPS                              #
##################################################################
feh --no-fehbg --bg-fill my_wallpapers/TvwN4ws.png  
#~/.fehbg &
# hsetroot -solid $(getxres background)
~/.config/polybar/launch.sh &
#:~/.config/bspwm/bin/bspborder &
setxkbmap -model abnt2 -layout br -variant abnt2
picom &
mpDris2 & 
#pulseeffects --gapplication-service &
dunst &
# pgrep xflux || xflux -l 43.36 -g 1.26 &
udiskie &
# pkill 2bspwm ; 2bspwm &
# pkill flashfocus ; flashfocus &

# Fix cursor.
xsetroot -cursor_name left_ptr 
