#! /bin/sh
#
#
#    ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ 
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░   
#     ░            ░               ░           ░   
#          ░                                       
#

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 


bspc config border_width         0
bspc config window_gap          13
config window_gap 10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

rule -a min                follow=on focus=on
rule -a Code                        follow=on focus=on
rule -a min                 follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating


${HOME}/.fehbg
${HOME}/.config/polybar/launch.sh
picom --config $HOME/.config/picom/picom.conf & 


# Fix cursor.
xsetroot -cursor_name left_ptr 
